version: '3'
services:
  frontend:
    image: node:8.11.3
    container_name: frontend
    working_dir: /usr/src/app
    command: npm start
    env_file: 
      - .env
    volumes:
      - './vclothesUI:/usr/src/app'
    expose: 
      - ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend

  backend:
    image: node:8.11.3
    container_name: backend
    working_dir: /usr/src/app
    command: "npm start"
    env_file: 
      - .env
    volumes:
      - './vclothes-backend:/usr/src/app'
    expose: 
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.24
    container_name: mysql
    env_file:
      - .env
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_PORT}

volumes:
  db-data:
    driver: local
